### ISSUE TITLE
stdlib again

### ISSUE THREAD

**Issue by mukkid** [georgeglessner/RedditImageBot#10]
https://github.com/georgeglessner/RedditImageBot/blob/2179b60a84860d6433d620f0872dd7c19ac9bc33/image.py#L55

Consider something like 
```
root, _ = os.path.splitext(img_url)
img_url = root + '.gif'
```

Additional nitpick, perhaps leave a comment for why you're modifying .gifv files

**Comment by georgeglessner** [comment]
Fixed, thanks!
