### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by mukkid** [georgeglessner/RedditImageBot#13]
https://github.com/georgeglessner/RedditImageBot/blob/bc4dc35717c172c56378d50080120561d48d94e5/image.py#L12

I know you've said to create an images folder in the cwd, but it could be cool to create it for them if it doesn't exist. 
https://docs.python.org/2/library/os.html#os.mkdir
Additionally, it would be even cooler if the user could specify a custom images folder path in a config file.

**Comment by georgeglessner** [comment]
Added code to create images folder if one does not exist, will look into last suggestion
