### ISSUE TITLE
Feature suggestion (cmdline)

### ISSUE THREAD

**Issue by mukkid** [georgeglessner/RedditImageBot#15]
It would also be cool if you could run the entire command from the command line (i.e. without entering interactive mode)

something like:
`$ python image.py -s birdswitharms -n 7`

and it would just run. ( Download 7 images from /r/birdswitharms)

If you were interested, look into https://docs.python.org/2/howto/argparse.html

**Comment by georgeglessner** [comment]
Added, thanks!
