### ISSUE TITLE
Return code

### ISSUE THREAD

**Issue by mukkid** [georgeglessner/RedditImageBot#2]
https://github.com/georgeglessner/RedditImageBot/blob/f34181c3012c62d04cd5a7e178295471a5b34636/imgurbot.py#L26

For the most part, an error should be reported with a non-zero return code (usually 1 but it varies). 
i.e.`sys.exit(1)`

If you think that no subreddits being found is an error, consider this change.

**Comment by georgeglessner** [comment]
Fixed, thanks!
