### ISSUE TITLE
nitpick

### ISSUE THREAD

**Issue by mukkid** [georgeglessner/RedditImageBot#9]
https://github.com/georgeglessner/RedditImageBot/blob/2179b60a84860d6433d620f0872dd7c19ac9bc33/image.py#L45

You can save yourself 1 line by unpacking the result of `os.path.splitext`
e.g.
```
_, extension = os.path.splitext(img_url)
if extension in ['.jpg', '.gif', '.peg', '.png']:
    ....
    ....
```

**Comment by georgeglessner** [comment]
Fixed, thanks!
